services:
  - type: web
    name: meusiteflask
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash setup_wkhtml.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
